/*
 * This file has been auto-generated by CppUTestMock v0.4.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "returnint2.h"
}

#include <CppUTestExt/MockSupport.h>

int intreturner2(int a)
{
    return mock().actualCall("intreturner2").withIntParameter("a", a).returnIntValue();
}

